# Generated by Django 3.0 on 2021-05-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210504_1701'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='image1',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
