# Generated by Django 3.0 on 2021-05-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210504_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='account',
            name='image3',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
