# Generated by Django 3.0 on 2021-05-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_door'),
    ]

    operations = [
        migrations.RenameField(
            model_name='door',
            old_name='status',
            new_name='is_open',
        ),
    ]
