# Generated by Django 3.0 on 2021-05-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inside',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('entry_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('door_id', models.IntegerField(null=True)),
            ],
        ),
    ]
