# Generated by Django 3.0 on 2021-05-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_camera'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
