# Generated by Django 3.0 on 2021-05-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_camera_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedValueFromScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_value', models.IntegerField(null=True)),
            ],
        ),
    ]
