# Generated by Django 3.0 on 2021-05-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20210511_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inside',
            name='exit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
