# Generated by Django 3.0 on 2021-05-12 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210511_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inside',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
