# Generated by Django 3.0 on 2021-05-12 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20210512_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='data_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data_joined'),
        ),
        migrations.AlterField(
            model_name='qr',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
